### ISSUE TITLE
Streaming Server is not available

### ISSUE THREAD

**Issue by yj-yjh-yj** [psyb0t/safe-stremio#1]
Hi, 

Found this docker image and it's super great and helpful. I got the docker image running, open it up with http://<my host>:8080, all good, but it complains "Streaming Server is not available", i tried to install this stream-service on my ubuntu 22.04 following the chatgpt tutorial but the "stremio-service.service - Stremio Service" failed, do you have any tutorial to install this? or am i on the wrong path?

Thank you so much for the help.

**Comment by Korben00** [comment]
Hi,

Try this : https://github.com/psyb0t/safe-stremio/pull/2

**Comment by psyb0t** [comment]
> Hi,
> 
> Found this docker image and it's super great and helpful. I got the docker image running, open it up with http://:8080, all good, but it complains "Streaming Server is not available", i tried to install this stream-service on my ubuntu 22.04 following the chatgpt tutorial but the "stremio-service.service - Stremio Service" failed, do you have any tutorial to install this? or am i on the wrong path?
> 
> Thank you so much for the help.

The solution to that is this: https://github.com/psyb0t/safe-stremio/tree/master?tab=readme-ov-file#final-steps

Checking the solution that @Korben00 came up with now.

**Comment by psyb0t** [comment]
Okay so the solution to that remains this: https://github.com/psyb0t/safe-stremio/tree/master?tab=readme-ov-file#final-steps. @yinjiehuang pls confirm that it's working on your end so that I can close this issue.

**Comment by yj-yjh-yj** [comment]
works fine now! Thank you folks!

**Comment by psyb0t** [comment]
@yinjiehuang awesome! 🖤🖤 closing the issue now.
